# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.options import Options
#from selenium.webdriver.firefox.options import Options
class TestSmokeTest():
     
  def setup_method(self, method):
    options = Options()
    options.add_argument("--headless=new")
    #self.driver = webdriver.Firefox(options=options)
    self.driver = webdriver.Chrome(options=options)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_homepage(self):
    self.driver.get("http://127.0.0.1:5500/index.html")
    self.driver.set_window_size(1217, 692)
    WebDriverWait(self.driver, 20).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "a[href=\"index.html\"]")))
    self.driver.find_element(By.CSS_SELECTOR, "a[href=\"index.html\"]").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".header-logo img")
    assert len(elements) > 0
    assert self.driver.find_element(By.CSS_SELECTOR, ".header-title > h1").text == "Teton Idaho"
    assert self.driver.title == "Teton Idaho CoC"
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".spotlight1")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".spotlight2")
    assert len(elements) > 0
    self.driver.find_element(By.LINK_TEXT, "Join Us!").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "h3").text == "Welcome to the Teton Chamber of Commerce Signup Wizard!"
  
  def test_adminPage(self):
    self.driver.get("http://127.0.0.1:5500/index.html")
    self.driver.set_window_size(1217, 692)
    WebDriverWait(self.driver, 20).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "a[href=\"admin.html\"]")))
    self.driver.find_element(By.CSS_SELECTOR, "a[href=\"admin.html\"]").click()
    self.driver.find_element(By.ID, "password").send_keys("Password")
    self.driver.find_element(By.ID, "username").send_keys("Username")
    elements = self.driver.find_elements(By.ID, "username")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, ".mysubmit:nth-child(4)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".errorMessage").text == "Invalid username and password."
  
  def test_directoryPage(self):
    self.driver.get("http://127.0.0.1:5500/index.html")
    self.driver.set_window_size(1217, 692)
    WebDriverWait(self.driver, 20).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "a[href=\"directory.html\"]")))
    self.driver.find_element(By.CSS_SELECTOR, "a[href=\"directory.html\"]").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".gold-member:nth-child(9) > p:nth-child(2)").text == "Teton Turf and Tree"
    assert self.driver.find_element(By.CSS_SELECTOR, ".gold-member:nth-child(9) > p:nth-child(2)").text == "Teton Turf and Tree"
  
  def test_joinPage(self):
    self.driver.get("http://127.0.0.1:5500/index.html")
    self.driver.set_window_size(1217, 692)
    WebDriverWait(self.driver, 20).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "a[href=\"join.html\"]")))
    self.driver.find_element(By.CSS_SELECTOR, "a[href=\"join.html\"]").click()
    elements = self.driver.find_elements(By.NAME, "fname")
    assert len(elements) > 0
    self.driver.find_element(By.NAME, "fname").click()
    self.driver.find_element(By.NAME, "fname").send_keys("juanito")
    self.driver.find_element(By.NAME, "lname").click()
    self.driver.find_element(By.NAME, "lname").send_keys("mena")
    self.driver.find_element(By.NAME, "bizname").click()
    self.driver.find_element(By.NAME, "bizname").send_keys("juanito el gato")
    self.driver.find_element(By.NAME, "biztitle").click()
    self.driver.find_element(By.NAME, "biztitle").send_keys("manager")
    self.driver.find_element(By.CSS_SELECTOR, "fieldset").click()
    WebDriverWait(self.driver, 20).until(expected_conditions.visibility_of_element_located((By.NAME, "submit")))
    self.driver.find_element(By.NAME, "submit").click()
    self.driver.find_element(By.NAME, "email").click()
    elements = self.driver.find_elements(By.NAME, "email")
    assert len(elements) > 0
  
  
